### ISSUE TITLE
Failing: Using meteor --settings to create admin user

### ISSUE THREAD

**Issue by jkanyua** [andela/arakari-rc#11]
For bugs, please fill out the three following sections completely

### Expected behavior
- New Installation should create an admin user and print on console

### Actual Behavior
- Fails at step -> Using meteor --settings to create admin user

### Steps to Reproduce the Behavior
- Clone Repo ```git clone https://github.com/andela/arakari-rc.git```
- Run ``` meteor npm install ```
- Install Fails with error: ```Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.```  after step ```Using meteor --settings to create admin user.```

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by warenga** [comment]
Fixed on PR: `#141119741 Fix create admin bug`

**Comment by warenga** [comment]
The problem was that `Meteor.user()` was being called in a published function as opposed to a meteor method. So I created a meteor method that returned `Meteor.user()`.
